from datetime import datetime, timedelta, timezone

from backend.event_model import SecurityEvent
from backend.alert_model import SecurityAlert
from detections.detection_engine import run_detections


def create_event(
    event_id: str,
    timestamp: datetime,
    event_type: str,
    action: str,
    process_path: str | None = None,
    file_path: str | None = None,
    source_ip: str | None = None,
    message: str = "Integration test event",
) -> SecurityEvent:

    return SecurityEvent(
        event_id=event_id,
        timestamp=timestamp,
        host="test-host",
        event_type=event_type,
        action=action,
        source="test",
        severity="medium",
        username="testuser",
        source_ip=source_ip,
        description=message,
        subsystem="test",
        category=event_type,
        process_path=process_path,
        file_path=file_path,
        message_type="Default",
        raw_message=message,
    )


def test_detection_engine_runs_all_detection_rules():

    start_time = datetime.now(timezone.utc)

    events = []

    # ---------------------------------------------------------
    # 1. Five failed login attempts.
    #
    # Expected:
    # BRUTE FORCE
    # ---------------------------------------------------------

    for i in range(5):

        events.append(
            create_event(
                event_id=f"login-{i}",
                timestamp=start_time + timedelta(
                    seconds=i * 20
                ),
                event_type="authentication",
                action="login_failed",
                source_ip="192.168.1.50",
                message="Failed login attempt",
            )
        )

    # ---------------------------------------------------------
    # 2. Suspicious process.
    #
    # Expected:
    # SUSPICIOUS PROCESS
    # ---------------------------------------------------------

    events.append(
        create_event(
            event_id="process-1",
            timestamp=start_time + timedelta(seconds=120),
            event_type="process",
            action="process_started",
            process_path="/usr/bin/curl",
            message="Process started: /usr/bin/curl",
        )
    )

    # ---------------------------------------------------------
    # 3. Suspicious file activity.
    #
    # Expected:
    # SUSPICIOUS FILE ACTIVITY
    # ---------------------------------------------------------

    events.append(
        create_event(
            event_id="file-1",
            timestamp=start_time + timedelta(seconds=140),
            event_type="file",
            action="file_created",
            file_path="/tmp/payload.sh",
            message="File created: /tmp/payload.sh",
        )
    )

    # ---------------------------------------------------------
    # 4. Privilege escalation activity.
    #
    # Expected:
    # PRIVILEGE ESCALATION
    # ---------------------------------------------------------

    events.append(
        create_event(
            event_id="privilege-1",
            timestamp=start_time + timedelta(seconds=160),
            event_type="process",
            action="process_started",
            process_path="/usr/bin/sudo",
            message="Process started: /usr/bin/sudo",
        )
    )

    # ---------------------------------------------------------
    # 5. Suspicious network activity.
    #
    # Expected:
    # SUSPICIOUS NETWORK ACTIVITY
    # ---------------------------------------------------------

    events.append(
        create_event(
            event_id="network-1",
            timestamp=start_time + timedelta(seconds=180),
            event_type="network",
            action="network_connection",
            message=(
                "Connection established to "
                "192.168.1.20:4444"
            ),
        )
    )

    # ---------------------------------------------------------
    # Run the complete Detection Engine.
    # ---------------------------------------------------------

    alerts = run_detections(events)

    # Every alert must use the standardized alert model.
    assert all(
        isinstance(alert, SecurityAlert)
        for alert in alerts
    )

    # Extract the attack types.
    attack_types = {
        alert.attack_type
        for alert in alerts
    }

    # Verify all five detection capabilities fired.
    assert "Brute Force" in attack_types
    assert "Suspicious Process" in attack_types
    assert "Suspicious File Activity" in attack_types
    assert "Privilege Escalation" in attack_types
    assert "Suspicious Network Activity" in attack_types

    # One alert should be generated by each rule.
    assert len(alerts) == 5